approvals_reviewer = "user"
profile = "codespace"

[profiles.codespace]
sandbox_mode = "danger-full-access"
ask_for_approval = "never"

[projects."/workspaces/bus-mgmt-benchmarks-dolt-db"]
trust_level = "trusted"

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true
